# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'elastix_plugin.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_elastixMain(object):
    def setupUi(self, elastixMain):
        elastixMain.setObjectName("elastixMain")
        elastixMain.resize(850, 600)
        elastixMain.setMinimumSize(QtCore.QSize(850, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/elastix_logo_48.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        elastixMain.setWindowIcon(icon)
        self.tabWidget = QtWidgets.QTabWidget(elastixMain)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 831, 581))
        self.tabWidget.setToolTip("")
        self.tabWidget.setObjectName("tabWidget")
        self.tabLoad = QtWidgets.QWidget()
        self.tabLoad.setObjectName("tabLoad")
        self.sampleStackName = QtWidgets.QLabel(self.tabLoad)
        self.sampleStackName.setGeometry(QtCore.QRect(200, 60, 251, 16))
        self.sampleStackName.setMinimumSize(QtCore.QSize(250, 0))
        self.sampleStackName.setText("")
        self.sampleStackName.setObjectName("sampleStackName")
        self.instructionsLabelTabLoad = QtWidgets.QLabel(self.tabLoad)
        self.instructionsLabelTabLoad.setGeometry(QtCore.QRect(20, 260, 781, 171))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.instructionsLabelTabLoad.setFont(font)
        self.instructionsLabelTabLoad.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.instructionsLabelTabLoad.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.instructionsLabelTabLoad.setWordWrap(True)
        self.instructionsLabelTabLoad.setObjectName("instructionsLabelTabLoad")
        self.layoutWidget = QtWidgets.QWidget(self.tabLoad)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 801, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.loadMoving = QtWidgets.QPushButton(self.layoutWidget)
        self.loadMoving.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadMoving.sizePolicy().hasHeightForWidth())
        self.loadMoving.setSizePolicy(sizePolicy)
        self.loadMoving.setMinimumSize(QtCore.QSize(180, 0))
        self.loadMoving.setObjectName("loadMoving")
        self.horizontalLayout_2.addWidget(self.loadMoving)
        self.movingStackName = QtWidgets.QLabel(self.layoutWidget)
        self.movingStackName.setMinimumSize(QtCore.QSize(250, 0))
        self.movingStackName.setText("")
        self.movingStackName.setObjectName("movingStackName")
        self.horizontalLayout_2.addWidget(self.movingStackName)
        spacerItem = QtWidgets.QSpacerItem(328, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.layoutWidget1 = QtWidgets.QWidget(self.tabLoad)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 11, 801, 29))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadFixed = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadFixed.sizePolicy().hasHeightForWidth())
        self.loadFixed.setSizePolicy(sizePolicy)
        self.loadFixed.setMinimumSize(QtCore.QSize(180, 0))
        self.loadFixed.setObjectName("loadFixed")
        self.horizontalLayout.addWidget(self.loadFixed)
        self.referenceStackName = QtWidgets.QLabel(self.layoutWidget1)
        self.referenceStackName.setMinimumSize(QtCore.QSize(250, 0))
        self.referenceStackName.setText("")
        self.referenceStackName.setObjectName("referenceStackName")
        self.horizontalLayout.addWidget(self.referenceStackName)
        spacerItem1 = QtWidgets.QSpacerItem(318, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.layoutWidget2 = QtWidgets.QWidget(self.tabLoad)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 80, 811, 141))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget2)
        self.groupBox.setMinimumSize(QtCore.QSize(101, 0))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 30, 87, 95))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.flipAxis1 = QtWidgets.QPushButton(self.layoutWidget3)
        self.flipAxis1.setEnabled(False)
        self.flipAxis1.setObjectName("flipAxis1")
        self.verticalLayout.addWidget(self.flipAxis1)
        self.flipAxis2 = QtWidgets.QPushButton(self.layoutWidget3)
        self.flipAxis2.setEnabled(False)
        self.flipAxis2.setObjectName("flipAxis2")
        self.verticalLayout.addWidget(self.flipAxis2)
        self.flipAxis3 = QtWidgets.QPushButton(self.layoutWidget3)
        self.flipAxis3.setEnabled(False)
        self.flipAxis3.setObjectName("flipAxis3")
        self.verticalLayout.addWidget(self.flipAxis3)
        self.horizontalLayout_5.addWidget(self.groupBox)
        spacerItem3 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget2)
        self.groupBox_2.setMinimumSize(QtCore.QSize(101, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 30, 87, 95))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rotAxis1 = QtWidgets.QPushButton(self.layoutWidget4)
        self.rotAxis1.setEnabled(False)
        self.rotAxis1.setObjectName("rotAxis1")
        self.verticalLayout_2.addWidget(self.rotAxis1)
        self.rotAxis2 = QtWidgets.QPushButton(self.layoutWidget4)
        self.rotAxis2.setEnabled(False)
        self.rotAxis2.setObjectName("rotAxis2")
        self.verticalLayout_2.addWidget(self.rotAxis2)
        self.rotAxis3 = QtWidgets.QPushButton(self.layoutWidget4)
        self.rotAxis3.setEnabled(False)
        self.rotAxis3.setObjectName("rotAxis3")
        self.verticalLayout_2.addWidget(self.rotAxis3)
        self.horizontalLayout_5.addWidget(self.groupBox_2)
        spacerItem4 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.layoutWidget2)
        self.groupBox_3.setMinimumSize(QtCore.QSize(101, 0))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 30, 87, 95))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.swapAxis1_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.swapAxis1_2.setEnabled(False)
        self.swapAxis1_2.setObjectName("swapAxis1_2")
        self.verticalLayout_3.addWidget(self.swapAxis1_2)
        self.swapAxis2_3 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.swapAxis2_3.setEnabled(False)
        self.swapAxis2_3.setObjectName("swapAxis2_3")
        self.verticalLayout_3.addWidget(self.swapAxis2_3)
        self.swapAxis3_1 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.swapAxis3_1.setEnabled(False)
        self.swapAxis3_1.setObjectName("swapAxis3_1")
        self.verticalLayout_3.addWidget(self.swapAxis3_1)
        self.horizontalLayout_5.addWidget(self.groupBox_3)
        spacerItem5 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.saveModifiedMovingStack = QtWidgets.QPushButton(self.layoutWidget2)
        self.saveModifiedMovingStack.setEnabled(False)
        self.saveModifiedMovingStack.setMinimumSize(QtCore.QSize(200, 0))
        self.saveModifiedMovingStack.setObjectName("saveModifiedMovingStack")
        self.horizontalLayout_5.addWidget(self.saveModifiedMovingStack)
        spacerItem6 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.label = QtWidgets.QLabel(self.tabLoad)
        self.label.setGeometry(QtCore.QRect(350, 450, 101, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/icons/elastix_logo_96.gif"))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tabLoad, "")
        self.tabCommand = QtWidgets.QWidget()
        self.tabCommand.setObjectName("tabCommand")
        self.frameCommand = QtWidgets.QFrame(self.tabCommand)
        self.frameCommand.setGeometry(QtCore.QRect(10, 440, 801, 101))
        self.frameCommand.setFrameShape(QtWidgets.QFrame.Box)
        self.frameCommand.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCommand.setObjectName("frameCommand")
        self.labelCommandText = QtWidgets.QLabel(self.frameCommand)
        self.labelCommandText.setGeometry(QtCore.QRect(10, 20, 781, 71))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelCommandText.setFont(font)
        self.labelCommandText.setText("")
        self.labelCommandText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelCommandText.setWordWrap(True)
        self.labelCommandText.setObjectName("labelCommandText")
        self.labelCommand = QtWidgets.QLabel(self.frameCommand)
        self.labelCommand.setGeometry(QtCore.QRect(10, 0, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelCommand.setFont(font)
        self.labelCommand.setObjectName("labelCommand")
        self.label_selectOutputDir = QtWidgets.QLabel(self.tabCommand)
        self.label_selectOutputDir.setGeometry(QtCore.QRect(20, 40, 661, 16))
        self.label_selectOutputDir.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_selectOutputDir.setFont(font)
        self.label_selectOutputDir.setObjectName("label_selectOutputDir")
        self.label_selectParamFiles = QtWidgets.QLabel(self.tabCommand)
        self.label_selectParamFiles.setGeometry(QtCore.QRect(20, 260, 701, 16))
        self.label_selectParamFiles.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_selectParamFiles.setFont(font)
        self.label_selectParamFiles.setObjectName("label_selectParamFiles")
        self.paramListView = QtWidgets.QListView(self.tabCommand)
        self.paramListView.setGeometry(QtCore.QRect(170, 280, 611, 111))
        self.paramListView.setObjectName("paramListView")
        self.loadParamFile = QtWidgets.QPushButton(self.tabCommand)
        self.loadParamFile.setGeometry(QtCore.QRect(20, 280, 150, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadParamFile.sizePolicy().hasHeightForWidth())
        self.loadParamFile.setSizePolicy(sizePolicy)
        self.loadParamFile.setMinimumSize(QtCore.QSize(150, 0))
        self.loadParamFile.setObjectName("loadParamFile")
        self.removeParameter = QtWidgets.QPushButton(self.tabCommand)
        self.removeParameter.setGeometry(QtCore.QRect(140, 360, 31, 31))
        self.removeParameter.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/edit-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.removeParameter.setIcon(icon1)
        self.removeParameter.setObjectName("removeParameter")
        self.outputDirSelect_button = QtWidgets.QPushButton(self.tabCommand)
        self.outputDirSelect_button.setGeometry(QtCore.QRect(10, 60, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputDirSelect_button.sizePolicy().hasHeightForWidth())
        self.outputDirSelect_button.setSizePolicy(sizePolicy)
        self.outputDirSelect_button.setMinimumSize(QtCore.QSize(0, 0))
        self.outputDirSelect_button.setObjectName("outputDirSelect_button")
        self.moveParamUp_button = QtWidgets.QPushButton(self.tabCommand)
        self.moveParamUp_button.setGeometry(QtCore.QRect(780, 280, 31, 31))
        self.moveParamUp_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/arrow-up.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.moveParamUp_button.setIcon(icon2)
        self.moveParamUp_button.setObjectName("moveParamUp_button")
        self.moveParamDown_button = QtWidgets.QPushButton(self.tabCommand)
        self.moveParamDown_button.setGeometry(QtCore.QRect(780, 360, 31, 31))
        self.moveParamDown_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/arrow-down.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.moveParamDown_button.setIcon(icon3)
        self.moveParamDown_button.setObjectName("moveParamDown_button")
        self.frame = QtWidgets.QFrame(self.tabCommand)
        self.frame.setGeometry(QtCore.QRect(70, 60, 741, 31))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.outputDir_label = QtWidgets.QLabel(self.frame)
        self.outputDir_label.setGeometry(QtCore.QRect(10, 4, 721, 21))
        self.outputDir_label.setText("")
        self.outputDir_label.setObjectName("outputDir_label")
        self.tabWidget.addTab(self.tabCommand, "")
        self.tabParameters = QtWidgets.QWidget()
        self.tabParameters.setObjectName("tabParameters")
        self.plainTextEditParam = QtWidgets.QPlainTextEdit(self.tabParameters)
        self.plainTextEditParam.setGeometry(QtCore.QRect(10, 10, 801, 501))
        self.plainTextEditParam.setObjectName("plainTextEditParam")
        self.comboBoxParam = QtWidgets.QComboBox(self.tabParameters)
        self.comboBoxParam.setGeometry(QtCore.QRect(10, 520, 291, 24))
        self.comboBoxParam.setObjectName("comboBoxParam")
        self.tabWidget.addTab(self.tabParameters, "")
        self.tabRun = QtWidgets.QWidget()
        self.tabRun.setObjectName("tabRun")
        self.runElastix_button = QtWidgets.QPushButton(self.tabRun)
        self.runElastix_button.setGeometry(QtCore.QRect(20, 20, 171, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.runElastix_button.setFont(font)
        self.runElastix_button.setObjectName("runElastix_button")
        self.frameCommand_3 = QtWidgets.QFrame(self.tabRun)
        self.frameCommand_3.setGeometry(QtCore.QRect(10, 440, 801, 101))
        self.frameCommand_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frameCommand_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCommand_3.setObjectName("frameCommand_3")
        self.labelCommandText_copy = QtWidgets.QLabel(self.frameCommand_3)
        self.labelCommandText_copy.setGeometry(QtCore.QRect(10, 20, 781, 71))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelCommandText_copy.setFont(font)
        self.labelCommandText_copy.setText("")
        self.labelCommandText_copy.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelCommandText_copy.setWordWrap(True)
        self.labelCommandText_copy.setObjectName("labelCommandText_copy")
        self.labelCommand_3 = QtWidgets.QLabel(self.frameCommand_3)
        self.labelCommand_3.setGeometry(QtCore.QRect(10, 0, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelCommand_3.setFont(font)
        self.labelCommand_3.setObjectName("labelCommand_3")
        self.runningRegistrations_ListView = QtWidgets.QListView(self.tabRun)
        self.runningRegistrations_ListView.setGeometry(QtCore.QRect(10, 70, 801, 361))
        self.runningRegistrations_ListView.setObjectName("runningRegistrations_ListView")
        self.label_2 = QtWidgets.QLabel(self.tabRun)
        self.label_2.setGeometry(QtCore.QRect(190, 50, 441, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tabRun, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.registrationResults_ListView = QtWidgets.QListView(self.tab)
        self.registrationResults_ListView.setGeometry(QtCore.QRect(10, 50, 801, 491))
        self.registrationResults_ListView.setObjectName("registrationResults_ListView")
        self.showHighlightedResult_radioButton = QtWidgets.QRadioButton(self.tab)
        self.showHighlightedResult_radioButton.setGeometry(QtCore.QRect(20, 20, 231, 21))
        self.showHighlightedResult_radioButton.setObjectName("showHighlightedResult_radioButton")
        self.showOriginalMovingImage_radioButton = QtWidgets.QRadioButton(self.tab)
        self.showOriginalMovingImage_radioButton.setGeometry(QtCore.QRect(320, 20, 231, 21))
        self.showOriginalMovingImage_radioButton.setChecked(True)
        self.showOriginalMovingImage_radioButton.setObjectName("showOriginalMovingImage_radioButton")
        self.tabWidget.addTab(self.tab, "")

        self.retranslateUi(elastixMain)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(elastixMain)

    def retranslateUi(self, elastixMain):
        _translate = QtCore.QCoreApplication.translate
        elastixMain.setWindowTitle(_translate("elastixMain", "Elastix plugin"))
        self.instructionsLabelTabLoad.setText(_translate("elastixMain", "Instructions \n"
"\n"
"1. Load a the image you wish to treat as the \"fixed\" (reference) image. \n"
"2. Load the image you wish to treat as the \"moving\" image. This will be registered to (1)\n"
"3. Ensure the sample and reference stack are in the same orientation. If not, flip the sample and save it. [not implemented yet]"))
        self.loadMoving.setText(_translate("elastixMain", "Load Moving Stack"))
        self.loadFixed.setText(_translate("elastixMain", "Load Fixed Stack"))
        self.groupBox.setTitle(_translate("elastixMain", "Flip"))
        self.flipAxis1.setText(_translate("elastixMain", "Axis 1"))
        self.flipAxis2.setText(_translate("elastixMain", "Axis 2"))
        self.flipAxis3.setText(_translate("elastixMain", "Axis 3"))
        self.groupBox_2.setTitle(_translate("elastixMain", "Rotate"))
        self.rotAxis1.setText(_translate("elastixMain", "Axis 1"))
        self.rotAxis2.setText(_translate("elastixMain", "Axis 2"))
        self.rotAxis3.setText(_translate("elastixMain", "Axis 3"))
        self.groupBox_3.setTitle(_translate("elastixMain", "Swap"))
        self.swapAxis1_2.setText(_translate("elastixMain", "1 / 2"))
        self.swapAxis2_3.setText(_translate("elastixMain", "2 / 3"))
        self.swapAxis3_1.setText(_translate("elastixMain", "3 / 1"))
        self.saveModifiedMovingStack.setText(_translate("elastixMain", "Save modified moving stack"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLoad), _translate("elastixMain", "Load"))
        self.labelCommand.setText(_translate("elastixMain", "Command"))
        self.label_selectOutputDir.setText(_translate("elastixMain", "1. Select output directory"))
        self.label_selectParamFiles.setText(_translate("elastixMain", "2. Choose parameter files (these are applied sequentially)"))
        self.loadParamFile.setText(_translate("elastixMain", "Load param file"))
        self.outputDirSelect_button.setText(_translate("elastixMain", "Select"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCommand), _translate("elastixMain", "Command"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabParameters), _translate("elastixMain", "Parameters"))
        self.runElastix_button.setText(_translate("elastixMain", "Run Elastix"))
        self.labelCommand_3.setText(_translate("elastixMain", "Command"))
        self.label_2.setText(_translate("elastixMain", "Currently running registrations"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRun), _translate("elastixMain", "Run"))
        self.showHighlightedResult_radioButton.setText(_translate("elastixMain", "Show &Highlighted Result"))
        self.showOriginalMovingImage_radioButton.setText(_translate("elastixMain", "Show &Original Moving Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("elastixMain", "Results"))

import elastix_plugin_rc
