# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'elastix_plugin.ui'
#
# Created: Wed Aug  5 17:27:29 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_elastixMain(object):
    def setupUi(self, elastixMain):
        elastixMain.setObjectName(_fromUtf8("elastixMain"))
        elastixMain.resize(850, 600)
        elastixMain.setMinimumSize(QtCore.QSize(850, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/elastix_logo.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        elastixMain.setWindowIcon(icon)
        self.tabWidget = QtGui.QTabWidget(elastixMain)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 801, 521))
        self.tabWidget.setToolTip(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabLoad = QtGui.QWidget()
        self.tabLoad.setObjectName(_fromUtf8("tabLoad"))
        self.sampleStackName = QtGui.QLabel(self.tabLoad)
        self.sampleStackName.setGeometry(QtCore.QRect(200, 60, 251, 16))
        self.sampleStackName.setMinimumSize(QtCore.QSize(250, 0))
        self.sampleStackName.setText(_fromUtf8(""))
        self.sampleStackName.setObjectName(_fromUtf8("sampleStackName"))
        self.instructionsLabelTabLoad = QtGui.QLabel(self.tabLoad)
        self.instructionsLabelTabLoad.setGeometry(QtCore.QRect(20, 260, 751, 171))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.instructionsLabelTabLoad.setFont(font)
        self.instructionsLabelTabLoad.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.instructionsLabelTabLoad.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.instructionsLabelTabLoad.setWordWrap(True)
        self.instructionsLabelTabLoad.setObjectName(_fromUtf8("instructionsLabelTabLoad"))
        self.widget = QtGui.QWidget(self.tabLoad)
        self.widget.setGeometry(QtCore.QRect(10, 40, 768, 26))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.loadSample = QtGui.QPushButton(self.widget)
        self.loadSample.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadSample.sizePolicy().hasHeightForWidth())
        self.loadSample.setSizePolicy(sizePolicy)
        self.loadSample.setMinimumSize(QtCore.QSize(180, 0))
        self.loadSample.setObjectName(_fromUtf8("loadSample"))
        self.horizontalLayout_2.addWidget(self.loadSample)
        self.sampleStackName_3 = QtGui.QLabel(self.widget)
        self.sampleStackName_3.setMinimumSize(QtCore.QSize(250, 0))
        self.sampleStackName_3.setText(_fromUtf8(""))
        self.sampleStackName_3.setObjectName(_fromUtf8("sampleStackName_3"))
        self.horizontalLayout_2.addWidget(self.sampleStackName_3)
        spacerItem = QtGui.QSpacerItem(328, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.widget1 = QtGui.QWidget(self.tabLoad)
        self.widget1.setGeometry(QtCore.QRect(11, 11, 758, 26))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.loadReference = QtGui.QPushButton(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadReference.sizePolicy().hasHeightForWidth())
        self.loadReference.setSizePolicy(sizePolicy)
        self.loadReference.setMinimumSize(QtCore.QSize(180, 0))
        self.loadReference.setObjectName(_fromUtf8("loadReference"))
        self.horizontalLayout.addWidget(self.loadReference)
        self.referenceStackName = QtGui.QLabel(self.widget1)
        self.referenceStackName.setMinimumSize(QtCore.QSize(250, 0))
        self.referenceStackName.setText(_fromUtf8(""))
        self.referenceStackName.setObjectName(_fromUtf8("referenceStackName"))
        self.horizontalLayout.addWidget(self.referenceStackName)
        spacerItem1 = QtGui.QSpacerItem(318, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.widget2 = QtGui.QWidget(self.tabLoad)
        self.widget2.setGeometry(QtCore.QRect(0, 80, 792, 141))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem2 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.groupBox = QtGui.QGroupBox(self.widget2)
        self.groupBox.setMinimumSize(QtCore.QSize(101, 0))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.widget3 = QtGui.QWidget(self.groupBox)
        self.widget3.setGeometry(QtCore.QRect(20, 30, 65, 82))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget3)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.flipAxis1 = QtGui.QPushButton(self.widget3)
        self.flipAxis1.setEnabled(False)
        self.flipAxis1.setObjectName(_fromUtf8("flipAxis1"))
        self.verticalLayout.addWidget(self.flipAxis1)
        self.flipAxis2 = QtGui.QPushButton(self.widget3)
        self.flipAxis2.setEnabled(False)
        self.flipAxis2.setObjectName(_fromUtf8("flipAxis2"))
        self.verticalLayout.addWidget(self.flipAxis2)
        self.flipAxis3 = QtGui.QPushButton(self.widget3)
        self.flipAxis3.setEnabled(False)
        self.flipAxis3.setObjectName(_fromUtf8("flipAxis3"))
        self.verticalLayout.addWidget(self.flipAxis3)
        self.horizontalLayout_5.addWidget(self.groupBox)
        spacerItem3 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.groupBox_2 = QtGui.QGroupBox(self.widget2)
        self.groupBox_2.setMinimumSize(QtCore.QSize(101, 0))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 65, 82))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.rotAxis1 = QtGui.QPushButton(self.layoutWidget)
        self.rotAxis1.setEnabled(False)
        self.rotAxis1.setObjectName(_fromUtf8("rotAxis1"))
        self.verticalLayout_2.addWidget(self.rotAxis1)
        self.rotAxis2 = QtGui.QPushButton(self.layoutWidget)
        self.rotAxis2.setEnabled(False)
        self.rotAxis2.setObjectName(_fromUtf8("rotAxis2"))
        self.verticalLayout_2.addWidget(self.rotAxis2)
        self.rotAxis3 = QtGui.QPushButton(self.layoutWidget)
        self.rotAxis3.setEnabled(False)
        self.rotAxis3.setObjectName(_fromUtf8("rotAxis3"))
        self.verticalLayout_2.addWidget(self.rotAxis3)
        self.horizontalLayout_5.addWidget(self.groupBox_2)
        spacerItem4 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.groupBox_3 = QtGui.QGroupBox(self.widget2)
        self.groupBox_3.setMinimumSize(QtCore.QSize(101, 0))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 30, 70, 82))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.swapAxis1_2 = QtGui.QPushButton(self.layoutWidget_2)
        self.swapAxis1_2.setEnabled(False)
        self.swapAxis1_2.setObjectName(_fromUtf8("swapAxis1_2"))
        self.verticalLayout_3.addWidget(self.swapAxis1_2)
        self.swapAxis2_3 = QtGui.QPushButton(self.layoutWidget_2)
        self.swapAxis2_3.setEnabled(False)
        self.swapAxis2_3.setObjectName(_fromUtf8("swapAxis2_3"))
        self.verticalLayout_3.addWidget(self.swapAxis2_3)
        self.swapAxis3_1 = QtGui.QPushButton(self.layoutWidget_2)
        self.swapAxis3_1.setEnabled(False)
        self.swapAxis3_1.setObjectName(_fromUtf8("swapAxis3_1"))
        self.verticalLayout_3.addWidget(self.swapAxis3_1)
        self.horizontalLayout_5.addWidget(self.groupBox_3)
        spacerItem5 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.pushButton = QtGui.QPushButton(self.widget2)
        self.pushButton.setEnabled(False)
        self.pushButton.setMinimumSize(QtCore.QSize(200, 0))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_5.addWidget(self.pushButton)
        spacerItem6 = QtGui.QSpacerItem(168, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.tabWidget.addTab(self.tabLoad, _fromUtf8(""))
        self.tabCommand = QtGui.QWidget()
        self.tabCommand.setObjectName(_fromUtf8("tabCommand"))
        self.frameCommand = QtGui.QFrame(self.tabCommand)
        self.frameCommand.setGeometry(QtCore.QRect(10, 410, 771, 80))
        self.frameCommand.setFrameShape(QtGui.QFrame.Box)
        self.frameCommand.setFrameShadow(QtGui.QFrame.Raised)
        self.frameCommand.setObjectName(_fromUtf8("frameCommand"))
        self.labelCommandText = QtGui.QLabel(self.frameCommand)
        self.labelCommandText.setGeometry(QtCore.QRect(10, 20, 751, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelCommandText.setFont(font)
        self.labelCommandText.setText(_fromUtf8(""))
        self.labelCommandText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelCommandText.setWordWrap(True)
        self.labelCommandText.setObjectName(_fromUtf8("labelCommandText"))
        self.labelCommand = QtGui.QLabel(self.frameCommand)
        self.labelCommand.setGeometry(QtCore.QRect(10, 0, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelCommand.setFont(font)
        self.labelCommand.setObjectName(_fromUtf8("labelCommand"))
        self.label_SelectFixedImage = QtGui.QLabel(self.tabCommand)
        self.label_SelectFixedImage.setGeometry(QtCore.QRect(20, 20, 281, 16))
        self.label_SelectFixedImage.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_SelectFixedImage.setFont(font)
        self.label_SelectFixedImage.setObjectName(_fromUtf8("label_SelectFixedImage"))
        self.radioButtonSampleFixed = QtGui.QRadioButton(self.tabCommand)
        self.radioButtonSampleFixed.setGeometry(QtCore.QRect(20, 50, 261, 21))
        self.radioButtonSampleFixed.setMinimumSize(QtCore.QSize(160, 0))
        self.radioButtonSampleFixed.setToolTip(_fromUtf8(""))
        self.radioButtonSampleFixed.setChecked(True)
        self.radioButtonSampleFixed.setObjectName(_fromUtf8("radioButtonSampleFixed"))
        self.radioButtonReferenceFixed = QtGui.QRadioButton(self.tabCommand)
        self.radioButtonReferenceFixed.setGeometry(QtCore.QRect(300, 50, 261, 21))
        self.radioButtonReferenceFixed.setMinimumSize(QtCore.QSize(260, 0))
        self.radioButtonReferenceFixed.setObjectName(_fromUtf8("radioButtonReferenceFixed"))
        self.label_5 = QtGui.QLabel(self.tabCommand)
        self.label_5.setGeometry(QtCore.QRect(30, 80, 231, 71))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tabCommand)
        self.label_6.setGeometry(QtCore.QRect(300, 80, 231, 71))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_selectOutputDir = QtGui.QLabel(self.tabCommand)
        self.label_selectOutputDir.setGeometry(QtCore.QRect(20, 170, 281, 16))
        self.label_selectOutputDir.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_selectOutputDir.setFont(font)
        self.label_selectOutputDir.setObjectName(_fromUtf8("label_selectOutputDir"))
        self.label_selectParamFiles = QtGui.QLabel(self.tabCommand)
        self.label_selectParamFiles.setGeometry(QtCore.QRect(20, 260, 281, 16))
        self.label_selectParamFiles.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_selectParamFiles.setFont(font)
        self.label_selectParamFiles.setObjectName(_fromUtf8("label_selectParamFiles"))
        self.paramListView = QtGui.QListView(self.tabCommand)
        self.paramListView.setGeometry(QtCore.QRect(205, 280, 571, 111))
        self.paramListView.setObjectName(_fromUtf8("paramListView"))
        self.loadParamFile = QtGui.QPushButton(self.tabCommand)
        self.loadParamFile.setGeometry(QtCore.QRect(20, 280, 180, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadParamFile.sizePolicy().hasHeightForWidth())
        self.loadParamFile.setSizePolicy(sizePolicy)
        self.loadParamFile.setMinimumSize(QtCore.QSize(180, 0))
        self.loadParamFile.setObjectName(_fromUtf8("loadParamFile"))
        self.removeParameter = QtGui.QPushButton(self.tabCommand)
        self.removeParameter.setGeometry(QtCore.QRect(170, 360, 31, 31))
        self.removeParameter.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/edit-delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.removeParameter.setIcon(icon1)
        self.removeParameter.setObjectName(_fromUtf8("removeParameter"))
        self.outputDirSelectBox = QtGui.QPlainTextEdit(self.tabCommand)
        self.outputDirSelectBox.setGeometry(QtCore.QRect(20, 190, 691, 31))
        self.outputDirSelectBox.setObjectName(_fromUtf8("outputDirSelectBox"))
        self.dirMessageLabel = QtGui.QLabel(self.tabCommand)
        self.dirMessageLabel.setGeometry(QtCore.QRect(30, 220, 471, 16))
        self.dirMessageLabel.setText(_fromUtf8(""))
        self.dirMessageLabel.setObjectName(_fromUtf8("dirMessageLabel"))
        self.outputDir = QtGui.QPushButton(self.tabCommand)
        self.outputDir.setGeometry(QtCore.QRect(720, 190, 61, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputDir.sizePolicy().hasHeightForWidth())
        self.outputDir.setSizePolicy(sizePolicy)
        self.outputDir.setMinimumSize(QtCore.QSize(0, 0))
        self.outputDir.setObjectName(_fromUtf8("outputDir"))
        self.tabWidget.addTab(self.tabCommand, _fromUtf8(""))
        self.tabParameters = QtGui.QWidget()
        self.tabParameters.setObjectName(_fromUtf8("tabParameters"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tabParameters)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 10, 781, 431))
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.comboBoxParam = QtGui.QComboBox(self.tabParameters)
        self.comboBoxParam.setGeometry(QtCore.QRect(20, 450, 181, 24))
        self.comboBoxParam.setObjectName(_fromUtf8("comboBoxParam"))
        self.paramSave = QtGui.QPushButton(self.tabParameters)
        self.paramSave.setEnabled(False)
        self.paramSave.setGeometry(QtCore.QRect(230, 450, 95, 24))
        self.paramSave.setObjectName(_fromUtf8("paramSave"))
        self.tabWidget.addTab(self.tabParameters, _fromUtf8(""))
        self.tabRun = QtGui.QWidget()
        self.tabRun.setObjectName(_fromUtf8("tabRun"))
        self.runElastix = QtGui.QPushButton(self.tabRun)
        self.runElastix.setGeometry(QtCore.QRect(30, 40, 95, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.runElastix.setFont(font)
        self.runElastix.setObjectName(_fromUtf8("runElastix"))
        self.frameCommand_3 = QtGui.QFrame(self.tabRun)
        self.frameCommand_3.setGeometry(QtCore.QRect(10, 410, 771, 80))
        self.frameCommand_3.setFrameShape(QtGui.QFrame.Box)
        self.frameCommand_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frameCommand_3.setObjectName(_fromUtf8("frameCommand_3"))
        self.labelCommandText_copy = QtGui.QLabel(self.frameCommand_3)
        self.labelCommandText_copy.setGeometry(QtCore.QRect(10, 20, 751, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelCommandText_copy.setFont(font)
        self.labelCommandText_copy.setText(_fromUtf8(""))
        self.labelCommandText_copy.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelCommandText_copy.setWordWrap(True)
        self.labelCommandText_copy.setObjectName(_fromUtf8("labelCommandText_copy"))
        self.labelCommand_3 = QtGui.QLabel(self.frameCommand_3)
        self.labelCommand_3.setGeometry(QtCore.QRect(10, 0, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelCommand_3.setFont(font)
        self.labelCommand_3.setObjectName(_fromUtf8("labelCommand_3"))
        self.tabWidget.addTab(self.tabRun, _fromUtf8(""))

        self.retranslateUi(elastixMain)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(elastixMain)

    def retranslateUi(self, elastixMain):
        elastixMain.setWindowTitle(_translate("elastixMain", "Elastix plugin", None))
        self.instructionsLabelTabLoad.setText(_translate("elastixMain", "Instructions \n"
"\n"
"1. Load a reference stack. This should be the coordinate frame you want to go to. e.g. an average brain\n"
"2. Load a sample stack. This should be the stack that you want to explore in the standardised coordinates\n"
"3. Ensure the sample and reference stack are in the same orientation. If not, flip the sample and save it.", None))
        self.loadSample.setText(_translate("elastixMain", "Load Sample Stack", None))
        self.loadReference.setText(_translate("elastixMain", "Load Reference Stack", None))
        self.groupBox.setTitle(_translate("elastixMain", "Flip", None))
        self.flipAxis1.setText(_translate("elastixMain", "Axis 1", None))
        self.flipAxis2.setText(_translate("elastixMain", "Axis 2", None))
        self.flipAxis3.setText(_translate("elastixMain", "Axis 3", None))
        self.groupBox_2.setTitle(_translate("elastixMain", "Rotate", None))
        self.rotAxis1.setText(_translate("elastixMain", "Axis 1", None))
        self.rotAxis2.setText(_translate("elastixMain", "Axis 2", None))
        self.rotAxis3.setText(_translate("elastixMain", "Axis 3", None))
        self.groupBox_3.setTitle(_translate("elastixMain", "Swap", None))
        self.swapAxis1_2.setText(_translate("elastixMain", "1 / 2", None))
        self.swapAxis2_3.setText(_translate("elastixMain", "2 / 3", None))
        self.swapAxis3_1.setText(_translate("elastixMain", "3 / 1", None))
        self.pushButton.setText(_translate("elastixMain", "Save modified sample", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLoad), _translate("elastixMain", "Load", None))
        self.labelCommand.setText(_translate("elastixMain", "Command", None))
        self.label_SelectFixedImage.setText(_translate("elastixMain", "1. Select fixed image", None))
        self.radioButtonSampleFixed.setText(_translate("elastixMain", "sample image is fixed image", None))
        self.radioButtonReferenceFixed.setText(_translate("elastixMain", "reference image is fixed image", None))
        self.label_5.setText(_translate("elastixMain", "Select this if you have point data in the source space that you want to represent in the reference space.", None))
        self.label_6.setText(_translate("elastixMain", "Select this if you want the ource image to resemble the reference image.", None))
        self.label_selectOutputDir.setText(_translate("elastixMain", "2. Select output directory", None))
        self.label_selectParamFiles.setText(_translate("elastixMain", "3. Choose parameter files", None))
        self.loadParamFile.setText(_translate("elastixMain", "Load param file", None))
        self.outputDir.setText(_translate("elastixMain", "Select", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCommand), _translate("elastixMain", "Command", None))
        self.paramSave.setText(_translate("elastixMain", "Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabParameters), _translate("elastixMain", "Parameters", None))
        self.runElastix.setText(_translate("elastixMain", "Run", None))
        self.labelCommand_3.setText(_translate("elastixMain", "Command", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRun), _translate("elastixMain", "Run", None))

import elastix_plugin_rc
