# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transformix_plugin.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_transformix_plugin(object):
    def setupUi(self, transformix_plugin):
        transformix_plugin.setObjectName("transformix_plugin")
        transformix_plugin.resize(819, 269)
        transformix_plugin.setMinimumSize(QtCore.QSize(819, 269))
        transformix_plugin.setMaximumSize(QtCore.QSize(819, 269))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/elastix_logo_48.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        transformix_plugin.setWindowIcon(icon)
        self.frameCommand = QtWidgets.QFrame(transformix_plugin)
        self.frameCommand.setGeometry(QtCore.QRect(10, 120, 801, 101))
        self.frameCommand.setFrameShape(QtWidgets.QFrame.Box)
        self.frameCommand.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCommand.setObjectName("frameCommand")
        self.commandText_label = QtWidgets.QLabel(self.frameCommand)
        self.commandText_label.setGeometry(QtCore.QRect(10, 20, 781, 71))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.commandText_label.setFont(font)
        self.commandText_label.setText("")
        self.commandText_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.commandText_label.setWordWrap(True)
        self.commandText_label.setObjectName("commandText_label")
        self.labelCommand = QtWidgets.QLabel(self.frameCommand)
        self.labelCommand.setGeometry(QtCore.QRect(10, 0, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelCommand.setFont(font)
        self.labelCommand.setObjectName("labelCommand")
        self.layoutWidget = QtWidgets.QWidget(transformix_plugin)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 801, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chooseStack_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseStack_pushButton.sizePolicy().hasHeightForWidth())
        self.chooseStack_pushButton.setSizePolicy(sizePolicy)
        self.chooseStack_pushButton.setMinimumSize(QtCore.QSize(180, 0))
        self.chooseStack_pushButton.setObjectName("chooseStack_pushButton")
        self.horizontalLayout.addWidget(self.chooseStack_pushButton)
        self.stackName_label = QtWidgets.QLabel(self.layoutWidget)
        self.stackName_label.setMinimumSize(QtCore.QSize(250, 0))
        self.stackName_label.setText("")
        self.stackName_label.setObjectName("stackName_label")
        self.horizontalLayout.addWidget(self.stackName_label)
        spacerItem = QtWidgets.QSpacerItem(318, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.layoutWidget_2 = QtWidgets.QWidget(transformix_plugin)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 50, 801, 26))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chooseTransform_pushButton = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseTransform_pushButton.sizePolicy().hasHeightForWidth())
        self.chooseTransform_pushButton.setSizePolicy(sizePolicy)
        self.chooseTransform_pushButton.setMinimumSize(QtCore.QSize(180, 0))
        self.chooseTransform_pushButton.setObjectName("chooseTransform_pushButton")
        self.horizontalLayout_2.addWidget(self.chooseTransform_pushButton)
        self.transformName_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.transformName_label.setMinimumSize(QtCore.QSize(250, 0))
        self.transformName_label.setText("")
        self.transformName_label.setObjectName("transformName_label")
        self.horizontalLayout_2.addWidget(self.transformName_label)
        spacerItem1 = QtWidgets.QSpacerItem(318, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.frame_2 = QtWidgets.QFrame(transformix_plugin)
        self.frame_2.setGeometry(QtCore.QRect(70, 80, 741, 31))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.outputDir_label = QtWidgets.QLabel(self.frame_2)
        self.outputDir_label.setGeometry(QtCore.QRect(10, 4, 721, 21))
        self.outputDir_label.setText("")
        self.outputDir_label.setObjectName("outputDir_label")
        self.outputDirSelect_pushButton = QtWidgets.QPushButton(transformix_plugin)
        self.outputDirSelect_pushButton.setGeometry(QtCore.QRect(10, 80, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputDirSelect_pushButton.sizePolicy().hasHeightForWidth())
        self.outputDirSelect_pushButton.setSizePolicy(sizePolicy)
        self.outputDirSelect_pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.outputDirSelect_pushButton.setObjectName("outputDirSelect_pushButton")
        self.run_pushButton = QtWidgets.QPushButton(transformix_plugin)
        self.run_pushButton.setGeometry(QtCore.QRect(10, 230, 180, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_pushButton.sizePolicy().hasHeightForWidth())
        self.run_pushButton.setSizePolicy(sizePolicy)
        self.run_pushButton.setMinimumSize(QtCore.QSize(180, 0))
        self.run_pushButton.setObjectName("run_pushButton")
        self.loadResult_pushButton = QtWidgets.QPushButton(transformix_plugin)
        self.loadResult_pushButton.setGeometry(QtCore.QRect(220, 230, 180, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadResult_pushButton.sizePolicy().hasHeightForWidth())
        self.loadResult_pushButton.setSizePolicy(sizePolicy)
        self.loadResult_pushButton.setMinimumSize(QtCore.QSize(180, 0))
        self.loadResult_pushButton.setObjectName("loadResult_pushButton")

        self.retranslateUi(transformix_plugin)
        QtCore.QMetaObject.connectSlotsByName(transformix_plugin)

    def retranslateUi(self, transformix_plugin):
        _translate = QtCore.QCoreApplication.translate
        transformix_plugin.setWindowTitle(_translate("transformix_plugin", "Form"))
        self.labelCommand.setText(_translate("transformix_plugin", "Command"))
        self.chooseStack_pushButton.setText(_translate("transformix_plugin", "Choose Stack"))
        self.chooseTransform_pushButton.setText(_translate("transformix_plugin", "Choose Transform"))
        self.outputDirSelect_pushButton.setText(_translate("transformix_plugin", "Dir"))
        self.run_pushButton.setText(_translate("transformix_plugin", "Run"))
        self.loadResult_pushButton.setText(_translate("transformix_plugin", "Load result stack"))

import elastix_plugin_rc
