# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_line.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_addLine(object):
    def setupUi(self, addLine):
        addLine.setObjectName("addLine")
        addLine.resize(456, 445)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(addLine)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(addLine)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tableWidget = QtWidgets.QTableWidget(self.splitter)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(60)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(8)
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.name_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.verticalLayout.addWidget(self.name_lineEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.deg_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.deg_spinBox.setMinimum(1)
        self.deg_spinBox.setObjectName("deg_spinBox")
        self.horizontalLayout.addWidget(self.deg_spinBox)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.interactive_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.interactive_checkBox.setObjectName("interactive_checkBox")
        self.verticalLayout.addWidget(self.interactive_checkBox)
        self.addPoint_radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.addPoint_radioButton.setObjectName("addPoint_radioButton")
        self.verticalLayout.addWidget(self.addPoint_radioButton)
        self.removePoint_radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.removePoint_radioButton.setObjectName("removePoint_radioButton")
        self.verticalLayout.addWidget(self.removePoint_radioButton)
        self.fitType_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.fitType_comboBox.setObjectName("fitType_comboBox")
        self.verticalLayout.addWidget(self.fitType_comboBox)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.numPoints_textLabel = QtWidgets.QLabel(self.layoutWidget)
        self.numPoints_textLabel.setObjectName("numPoints_textLabel")
        self.verticalLayout.addWidget(self.numPoints_textLabel)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.fit_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.fit_pushButton.setObjectName("fit_pushButton")
        self.verticalLayout.addWidget(self.fit_pushButton)
        self.add_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.add_pushButton.setObjectName("add_pushButton")
        self.verticalLayout.addWidget(self.add_pushButton)
        self.verticalLayout_2.addWidget(self.splitter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.closeButton = QtWidgets.QPushButton(addLine)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_2.addWidget(self.closeButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.clear_pushButton = QtWidgets.QPushButton(addLine)
        self.clear_pushButton.setObjectName("clear_pushButton")
        self.horizontalLayout_2.addWidget(self.clear_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_3.setBuddy(self.name_lineEdit)
        self.label.setBuddy(self.deg_spinBox)

        self.retranslateUi(addLine)
        QtCore.QMetaObject.connectSlotsByName(addLine)

    def retranslateUi(self, addLine):
        _translate = QtCore.QCoreApplication.translate
        addLine.setWindowTitle(_translate("addLine", "add_lines"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("addLine", "Z"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("addLine", "X"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("addLine", "Y"))
        self.label_3.setText(_translate("addLine", "&Name:"))
        self.label.setText(_translate("addLine", "&deg"))
        self.interactive_checkBox.setText(_translate("addLine", "&interactive"))
        self.addPoint_radioButton.setText(_translate("addLine", "Add"))
        self.removePoint_radioButton.setText(_translate("addLine", "Remove"))
        self.numPoints_textLabel.setText(_translate("addLine", "n pts:"))
        self.fit_pushButton.setText(_translate("addLine", "&fit"))
        self.add_pushButton.setText(_translate("addLine", "&Add it!"))
        self.closeButton.setText(_translate("addLine", "&Close"))
        self.clear_pushButton.setText(_translate("addLine", "clear"))

